### ISSUE TITLE
Create DAO for Room implementation

### ISSUE THREAD

**Issue by geekanamika** [systers/powerup-android#1128]
## Description
As a developer,
I need DAO files with all required functions,
so that I can use it with the help of DataSource file for different SQL queries.

### Update [Required]
- [ ] Create new DAO files inside data directory

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
48 hours

**Comment by geekanamika** [comment]
Room implemented successfully in `gsoc18-infra` branch, closing issue.
