### ISSUE TITLE
Add PreGame setup to main flow of the game

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#1147]
## Description
As a developer,
I need add all the created screens for pregame setup to main flow of the app,
so that I can create the feature to choose NPCs.

## Mocks
Not applicablee

### Update [Required]
- [ ] Launch PreGame Setup after Avatar Room
- [ ] Populate grid view according to the choice made in initial screen

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 hours

**Comment by Rimjhim28** [comment]
Solved through #1149
