### ISSUE TITLE
Save user chosen pre game setup characters

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#1150]
## Description
As a developer,
I need save the npcs that user have chosen,
so that the asker in the game activity is updated accordingly.

## Mocks
Not applicable

### Update [Required]
- [ ] Save the chosen option in PowerUpUtils.java

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 hours

**Comment by Rimjhim28** [comment]
Solved through #1151
