### ISSUE TITLE
Add proper NPCs to Game Activity

### ISSUE THREAD

**Issue by Rimjhim28** [systers/powerup-android#1152]
## Description
As a developer,
I need to update the game activity to contain user chosen NPCs,
so that I can increase the UX.

## Mocks
Home Scenario should contain Sister
School scenario should contain Friend
Hospital scenario should contain Doctor
Library Scenario should contain Teacher 

### Update [Required]
- [ ] Modify GameActivity.java
### Enhancement to Update
- [ ] Update NPCs according to user chosen options

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by m-murad** [comment]
Fixed in  #1153
