### ISSUE TITLE
Fixing long parameter list codacy error for powerup

### ISSUE THREAD

**Issue by manjumegh** [systers/powerup-android#1161]
## Description
As a developer,
I need fix long list of parameter issue in https://github.com/systers/powerup-android/pull/1148/, more detail about issue is here:https://app.codacy.com/app/Systers/powerup-android/pullRequest?prid=1728500

### Update [Required]
- [ ] Create an additional class (wrapper class) and add long list param as class variables
- [ ] Use existing pattern to fix this issue

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
8 hours
