### ISSUE TITLE
Port PopupEventPlayer from iOS

### ISSUE THREAD

**Issue by justkd** [systers/powerup-android#1167]
## Description
As a developer,
I need to port PopupEventPlayer from the iOS version,
so that I can ensure both platforms have the same capability and can use generic datasets to design and implement this funtionality.

Popups should be overlays on the view that slide out from the side, animate an icon badge, can play a sound, and are automatically dismissed after a set time period (or manually dismissed by tapping on it).

The class and it's dependencies can be found in the OOC-Event-Classes folder:
```
PopupEventPlayer.swift
PopupEventModel.swift
PopupEvents.swift
Popups.json
```

It shares these dependencies with StorySequencePlayer:
```
SoundPlayer.swift
Animate.swift
```

Its use can be found in `ScenarioViewController.swift`, in the `handlePopupEvent(idNumber: String)` function.

## Mocks
![image.png](https://images.zenhubusercontent.com/5afe50b44b5806bc2bd3a78d/99c5ad18-7259-4d61-8fcb-ac278906dabf)

### Update [Required]
- [ ] Class should be ported such that:
- [ ] Popups can be instantiated in similar fashion (retrieve the popup data, call and add to the view)
- [ ] Popups use the same generic data parsed from Popups.json

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours
